### ISSUE TITLE
CI - round 2

### ISSUE THREAD

**Issue by bluescarni** [bluescarni/piranha#38]
Thanks to great work by @isuruf, now we have a continuous integration setup for both Linux (travis) and Windows (appveyor). This ticket tracks possible enhancements to the current CI setup.

For travis:
- [x] ~~OSX testing would be needed to cover the 3 most frequently used operating systems. This probably needs the `thread_local` issue to be worked around~~ (_done in #91_)
- [x] ~~now that a few large tests were split into smaller tests, it should be possible to add GCC 4.8 in Debug mode to the build~~ (_done in #40_)
- [x] ~~right now the Debug build takes quite a lot to run (45 minutes). We should investigate a parallel build with 2 parallel jobs in order to reduce the running time a bit. This might be especially important for a GCC debug build, as GCC is slower than clang~~ (_it turns out travis has a memory limit which does not allow parallel builds, at least at this time_)
- [ ] a couple of tests involving threading are disabled as they fail. The failures are likely related to some low-level threading functionality that might be disabled or not working properly in the travis VM. This should be investigated more and the test modified so that they handle the failure gracefully
- [x] ~~attempt to run the clang tests with the address sanitizer enabled~~ (_this is now done on GCC, see #48_)

For appveyor:
- [x] ~~the initial setup of the build can be shortened by providing a binary package for Boost (binary packages are already available for the other dependencies, but Boost is compiled each time)~~ (_@isuruf implemented caching in f29ad8539ca32fec74498a7b49f74bb47946cba5, which does something basically equivalent_)
- [x] ~~we should move to a Boost build that uses dynamic libraries rather than static ones, especially for the future testing of Python bindings (see below)~~ (_appveyor now uses dynamic libraries_)
- [x] ~~a test in appveyor is disabled (`series_03`) as apparently there is some issue with bzip2 (the test fails when trying to save a to disk a compressed serialised version of a series). This needs to be investigated~~ (_this was fixed with the new serialization API, see #78_)

General:
- [x] ~~we need to enable the compilation and testing of the Python bindings. These take a lot of memory and time to compile, so they should go in a separate build. The bindings should be compiled, installed and then tested via their Python test suite. It should not be too hard to do on linux, but on Windows it's gonna be more complicated as we need to build Boost dynamically, and provide a patched copy of the Python libraries~~  (_this is now done in #47 for travis_)
- [x] ~~coverage: enable coveralls~~ (_done in #53, only we use codecov instead of coveralls_)
- [x] ~~documentation: we should add a doc build that runs doxygen and checks that everything is documented properly. See https://github.com/Yelp/MOE/blob/master/.travis.yml for an updated doxygen package for travis~~ (_this is now done in #48, both for doxygen and sphinx_)
- [ ] 32-bit testing would also be good, as right now we test only 64-bit build on both Windows and linux
